Recipe App Rails final Commit
IsmailChangezi/recipe-app-rails pull request #20
Opened 2023-09-08 11:33 UTC by IsmailChangezi

## Description 
### All these requirements have been met
You should follow the layout of the wireframes provided. You should personalize the rest of the design including colors, typographies, spacings, etc.
Login page and registration page:
Should be built with Devise.
Food list (only for a group that has less than 3 members):
Should display a list of food added by the logged-in user as in the wireframe (display also quantity of a given food).
Should lead to a form that allows users to add new food.
Recipes list:
Should display a list of recipes created by the logged-in user as in the wireframe.
Should lead to recipe details.
If the user is the owner of the recipe, should allow the user to delete it.
Public recipe list:
Should display a list of all public recipes ordered by newest as in the wireframe.
Should lead to recipe details.
Recipe details:
Should display a toggle button that allows for a recipe to be made public or private.
If the recipe is public or the user is the owner of the recipe, should display the recipe details as in the wireframe.
If the user is the owner of the recipe, should lead to the form that allows the user to add new food.
General shopping list view (only for a group that has less than 3 members):
Should show the list of food that is missing for all recipes of the logged-in user (compare the list of food for all recipes with the general food list of that user).
Should count the total food items and total price of the missing food.
Make sure there are no N+1 queries happening.
Create a navigation menu that allows users to open all of the pages you created.
Write unit and integration tests

2023-09-08 13:56 UTC, cynthiainga requested changes
Hi @IsmailChangezi & @AliShahSafdari, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- [ ] Uses `Devise` for authentication ✔️ 
- [ ] Uses RSpec and Capybara testing libraries ✔️ 
- [ ] Follow GitHub flow and Gitflow ✔️ 
- [ ] No linters errors ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇🏾 👇🏾 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-08 13:56 UTC, cynthiainga commented on app/views/foods/index.html.erb
- [x] Good job so far but as mentioned in the project requirements you should follow the given wireframe and you can improve the design if you want but you should keep the given structure, and as we can see in the food page the `Create food` button is on the top to the right side. Also, make sure your table has lines that separate their columns 🙃 🙃 

Your design

<img width="964" alt="Screenshot 2023-09-08 at 15 35 33" src="https://github.com/IsmailChangezi/recipe-app-rails/assets/74501523/957d486b-46ed-4ab4-81da-c72e569cc135">

Given wireframe 

<img width="862" alt="Screenshot 2023-09-08 at 15 35 49" src="https://github.com/IsmailChangezi/recipe-app-rails/assets/74501523/8855a368-44d6-475e-8635-63f0303b6563">

2023-09-08 13:56 UTC, cynthiainga commented on app/views/recipes/_recipe.html.erb
- [ ] According to the wireframe each recipe has a remove button to the bottom, also the recipe name should display instead of the recipe id, for example, if my recipe is named `Pasta` it should display `Pasta` instead of `Recipe # 1`. Kindly fix that 🙃 

Your design

<img width="957" alt="Screenshot 2023-09-08 at 15 48 41" src="https://github.com/IsmailChangezi/recipe-app-rails/assets/74501523/5c8b8bb8-0142-4cd3-988e-68bbaeccf4dd">

Given wireframe

<img width="865" alt="Screenshot 2023-09-08 at 15 48 57" src="https://github.com/IsmailChangezi/recipe-app-rails/assets/74501523/53a88309-3323-463c-999d-09a566aab1a0">

2023-09-08 13:56 UTC, cynthiainga commented on app/views/recipes/show.html.erb
- [ ] Please kindly make sure you follow the given wireframe, the `Add ingredients` button is on the right side and the `Generate shopping list` on the left, also on the top is the name of the recipe that should display and not the recipe id 🙃 🙃 
- [ ] The `Add ingredients` button should lead to the form that allows us to add new food,the button helps us to add new food 'ingredients' that will display in the table below the two buttons not to edit the recipe and the ingredients in the table will help us to generate the shopping list by doing the sum of the ingredients on the list and displaying it on the shopping list page like shown in the wireframe. Kindly fix that 🙏🏾 

Your design

<img width="982" alt="Screenshot 2023-09-08 at 16 19 18" src="https://github.com/IsmailChangezi/recipe-app-rails/assets/74501523/90fbe2f9-07bb-4684-93bf-5ce04f55e6cd">

Given wireframe

<img width="632" alt="Screenshot 2023-09-08 at 16 19 34" src="https://github.com/IsmailChangezi/recipe-app-rails/assets/74501523/92a5d0e1-ccc5-42c4-884b-59a5766d9064">

2023-09-08 13:56 UTC, cynthiainga commented on app/views/public_recipes/index.html.erb
- [ ] Please kindly make sure to follow the given wireframe 🙃 

Your design

<img width="994" alt="Screenshot 2023-09-08 at 16 28 30" src="https://github.com/IsmailChangezi/recipe-app-rails/assets/74501523/d3bcbbe2-40a3-4a0c-8a15-886440aca04c">

Given Wireframe

<img width="869" alt="Screenshot 2023-09-08 at 16 28 45" src="https://github.com/IsmailChangezi/recipe-app-rails/assets/74501523/707f85e0-7b3d-430a-a735-bb6b3e0f842d">

2023-09-08 13:56 UTC, cynthiainga commented on app/views/home/_header.html.erb
> +          <%# <a class="nav-link" href="#">Features</a> %>
- [ ] Please kindly delete the commented lines of code to keep your code more clean 🙃

2023-09-08 13:56 UTC, cynthiainga commented on db/migrate/20230905150033_create_recipes.rb
> +      t.string :cooking_time
- [ ] I think the preparation and cooking time should be defined as time or float if you want and not string 🙃 , kindly fix that 🙏🏾

2023-09-08 15:00 UTC, AliShahSafdari commented on app/views/foods/index.html.erb
Thanks

2023-09-08 16:44 UTC, IsmailChangezi commented on app/views/recipes/show.html.erb
Hi @cynthiainga , 
We are a group of 2 I don't think the second requirement is for us.

2023-09-08 17:54 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights
-  Implemented some required changes. :heavy_check_mark: 
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-08 17:54 UTC, Qoosim commented on app/views/recipes/show.html.erb
> +        <button class="btn-bg-red-big ">Generate Shopping List</button>
- [ ] Great job implementing some required changes. This required changes from the previous reviewer is yet to be implemented. The Add ingredients button should lead to the form that allows the user to add new food, the button helps the user to add new food 'ingredients' that will display in the table below the two buttons not to edit the recipe and the ingredients in the table will help us to generate the shopping list by doing the sum of the ingredients on the list and displaying it on the shopping list page like shown in the wireframe. Kindly fix this issue.

### App Behaviours
[add-ingrea.webm](https://github.com/IsmailChangezi/recipe-app-rails/assets/26597432/84457d66-0a7e-49aa-be3a-c9fb96804888)

2023-09-09 07:05 UTC, Shedrack-Sunday approved these changes
Hi @IsmailChangezi  

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://github.com/krisbobo/blog-app/assets/50990925/76d09bb1-9dc7-46c0-be49-31f366afa4b8)


Highlights
- [x] Good project organization ✔️
- [x] Nice use of Rails features ✔️ 
- [x] Kudus on meeting the requirements suggested  ✔️

### Confirmed view:
![image](https://github.com/IsmailChangezi/recipe-app-rails/assets/50990925/422eee4d-6e12-4ddc-8fff-ff554a9673dd)

Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-09-09 12:43 UTC, merged